// Code generated by internal/gen. DO NOT EDIT.

package raoh

import "slices"

// fields0 is a set of 0 fields.
type fields0 struct {
	names []string
}

// Field returns the set with one more field, name, read with src.
func (f fields0) Field[A any](name string, src FieldSource[A]) fields1[A] {
	return fields1[A]{append(slices.Clip(f.names), name), toPart(name, src)}
}

func (f fields0) object() object0 { return object0{f: f} }

// object0 builds the decoder of an object of 0 fields.
type object0 struct {
	f      fields0
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object0) Strict() object0 {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object0) Map[R any](fn func() R) Decoder[any, R] {
	return o.AndThen(func() (R, error) { return fn(), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object0) AndThen[R any](fn func() (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn()
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object0) AndThenWithPath[R any](fn func(Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(at)
		return fromAbsoluteError(v, err)
	}}
}

// fields1 is a set of 1 fields.
type fields1[A any] struct {
	names []string
	p0    part[A]
}

// Field returns the set with one more field, name, read with src.
func (f fields1[A]) Field[B any](name string, src FieldSource[B]) fields2[A, B] {
	return fields2[A, B]{append(slices.Clip(f.names), name), f.p0, toPart(name, src)}
}

func (f fields1[A]) object() object1[A] { return object1[A]{f: f} }

// object1 builds the decoder of an object of 1 fields.
type object1[A any] struct {
	f      fields1[A]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object1[A]) Strict() object1[A] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object1[A]) Map[R any](fn func(A) R) Decoder[any, R] {
	return o.AndThen(func(v0 A) (R, error) { return fn(v0), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object1[A]) AndThen[R any](fn func(A) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object1[A]) AndThenWithPath[R any](fn func(A, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields2 is a set of 2 fields.
type fields2[A, B any] struct {
	names []string
	p0    part[A]
	p1    part[B]
}

// Field returns the set with one more field, name, read with src.
func (f fields2[A, B]) Field[C any](name string, src FieldSource[C]) fields3[A, B, C] {
	return fields3[A, B, C]{append(slices.Clip(f.names), name), f.p0, f.p1, toPart(name, src)}
}

func (f fields2[A, B]) object() object2[A, B] { return object2[A, B]{f: f} }

// object2 builds the decoder of an object of 2 fields.
type object2[A, B any] struct {
	f      fields2[A, B]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object2[A, B]) Strict() object2[A, B] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object2[A, B]) Map[R any](fn func(A, B) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B) (R, error) { return fn(v0, v1), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object2[A, B]) AndThen[R any](fn func(A, B) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object2[A, B]) AndThenWithPath[R any](fn func(A, B, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields3 is a set of 3 fields.
type fields3[A, B, C any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
}

// Field returns the set with one more field, name, read with src.
func (f fields3[A, B, C]) Field[D any](name string, src FieldSource[D]) fields4[A, B, C, D] {
	return fields4[A, B, C, D]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, toPart(name, src)}
}

func (f fields3[A, B, C]) object() object3[A, B, C] { return object3[A, B, C]{f: f} }

// object3 builds the decoder of an object of 3 fields.
type object3[A, B, C any] struct {
	f      fields3[A, B, C]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object3[A, B, C]) Strict() object3[A, B, C] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object3[A, B, C]) Map[R any](fn func(A, B, C) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C) (R, error) { return fn(v0, v1, v2), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object3[A, B, C]) AndThen[R any](fn func(A, B, C) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object3[A, B, C]) AndThenWithPath[R any](fn func(A, B, C, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields4 is a set of 4 fields.
type fields4[A, B, C, D any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
}

// Field returns the set with one more field, name, read with src.
func (f fields4[A, B, C, D]) Field[E any](name string, src FieldSource[E]) fields5[A, B, C, D, E] {
	return fields5[A, B, C, D, E]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, toPart(name, src)}
}

func (f fields4[A, B, C, D]) object() object4[A, B, C, D] { return object4[A, B, C, D]{f: f} }

// object4 builds the decoder of an object of 4 fields.
type object4[A, B, C, D any] struct {
	f      fields4[A, B, C, D]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object4[A, B, C, D]) Strict() object4[A, B, C, D] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object4[A, B, C, D]) Map[R any](fn func(A, B, C, D) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D) (R, error) { return fn(v0, v1, v2, v3), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object4[A, B, C, D]) AndThen[R any](fn func(A, B, C, D) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object4[A, B, C, D]) AndThenWithPath[R any](fn func(A, B, C, D, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields5 is a set of 5 fields.
type fields5[A, B, C, D, E any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
}

// Field returns the set with one more field, name, read with src.
func (f fields5[A, B, C, D, E]) Field[F any](name string, src FieldSource[F]) fields6[A, B, C, D, E, F] {
	return fields6[A, B, C, D, E, F]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, toPart(name, src)}
}

func (f fields5[A, B, C, D, E]) object() object5[A, B, C, D, E] { return object5[A, B, C, D, E]{f: f} }

// object5 builds the decoder of an object of 5 fields.
type object5[A, B, C, D, E any] struct {
	f      fields5[A, B, C, D, E]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object5[A, B, C, D, E]) Strict() object5[A, B, C, D, E] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object5[A, B, C, D, E]) Map[R any](fn func(A, B, C, D, E) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E) (R, error) { return fn(v0, v1, v2, v3, v4), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object5[A, B, C, D, E]) AndThen[R any](fn func(A, B, C, D, E) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object5[A, B, C, D, E]) AndThenWithPath[R any](fn func(A, B, C, D, E, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields6 is a set of 6 fields.
type fields6[A, B, C, D, E, F any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
}

// Field returns the set with one more field, name, read with src.
func (f fields6[A, B, C, D, E, F]) Field[G any](name string, src FieldSource[G]) fields7[A, B, C, D, E, F, G] {
	return fields7[A, B, C, D, E, F, G]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, toPart(name, src)}
}

func (f fields6[A, B, C, D, E, F]) object() object6[A, B, C, D, E, F] {
	return object6[A, B, C, D, E, F]{f: f}
}

// object6 builds the decoder of an object of 6 fields.
type object6[A, B, C, D, E, F any] struct {
	f      fields6[A, B, C, D, E, F]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object6[A, B, C, D, E, F]) Strict() object6[A, B, C, D, E, F] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object6[A, B, C, D, E, F]) Map[R any](fn func(A, B, C, D, E, F) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F) (R, error) { return fn(v0, v1, v2, v3, v4, v5), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object6[A, B, C, D, E, F]) AndThen[R any](fn func(A, B, C, D, E, F) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object6[A, B, C, D, E, F]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields7 is a set of 7 fields.
type fields7[A, B, C, D, E, F, G any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
}

// Field returns the set with one more field, name, read with src.
func (f fields7[A, B, C, D, E, F, G]) Field[H any](name string, src FieldSource[H]) fields8[A, B, C, D, E, F, G, H] {
	return fields8[A, B, C, D, E, F, G, H]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, toPart(name, src)}
}

func (f fields7[A, B, C, D, E, F, G]) object() object7[A, B, C, D, E, F, G] {
	return object7[A, B, C, D, E, F, G]{f: f}
}

// object7 builds the decoder of an object of 7 fields.
type object7[A, B, C, D, E, F, G any] struct {
	f      fields7[A, B, C, D, E, F, G]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object7[A, B, C, D, E, F, G]) Strict() object7[A, B, C, D, E, F, G] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object7[A, B, C, D, E, F, G]) Map[R any](fn func(A, B, C, D, E, F, G) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G) (R, error) { return fn(v0, v1, v2, v3, v4, v5, v6), nil })
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object7[A, B, C, D, E, F, G]) AndThen[R any](fn func(A, B, C, D, E, F, G) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object7[A, B, C, D, E, F, G]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields8 is a set of 8 fields.
type fields8[A, B, C, D, E, F, G, H any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
}

// Field returns the set with one more field, name, read with src.
func (f fields8[A, B, C, D, E, F, G, H]) Field[I any](name string, src FieldSource[I]) fields9[A, B, C, D, E, F, G, H, I] {
	return fields9[A, B, C, D, E, F, G, H, I]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, toPart(name, src)}
}

func (f fields8[A, B, C, D, E, F, G, H]) object() object8[A, B, C, D, E, F, G, H] {
	return object8[A, B, C, D, E, F, G, H]{f: f}
}

// object8 builds the decoder of an object of 8 fields.
type object8[A, B, C, D, E, F, G, H any] struct {
	f      fields8[A, B, C, D, E, F, G, H]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object8[A, B, C, D, E, F, G, H]) Strict() object8[A, B, C, D, E, F, G, H] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object8[A, B, C, D, E, F, G, H]) Map[R any](fn func(A, B, C, D, E, F, G, H) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object8[A, B, C, D, E, F, G, H]) AndThen[R any](fn func(A, B, C, D, E, F, G, H) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object8[A, B, C, D, E, F, G, H]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields9 is a set of 9 fields.
type fields9[A, B, C, D, E, F, G, H, I any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
}

// Field returns the set with one more field, name, read with src.
func (f fields9[A, B, C, D, E, F, G, H, I]) Field[J any](name string, src FieldSource[J]) fields10[A, B, C, D, E, F, G, H, I, J] {
	return fields10[A, B, C, D, E, F, G, H, I, J]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, toPart(name, src)}
}

func (f fields9[A, B, C, D, E, F, G, H, I]) object() object9[A, B, C, D, E, F, G, H, I] {
	return object9[A, B, C, D, E, F, G, H, I]{f: f}
}

// object9 builds the decoder of an object of 9 fields.
type object9[A, B, C, D, E, F, G, H, I any] struct {
	f      fields9[A, B, C, D, E, F, G, H, I]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object9[A, B, C, D, E, F, G, H, I]) Strict() object9[A, B, C, D, E, F, G, H, I] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object9[A, B, C, D, E, F, G, H, I]) Map[R any](fn func(A, B, C, D, E, F, G, H, I) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object9[A, B, C, D, E, F, G, H, I]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object9[A, B, C, D, E, F, G, H, I]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields10 is a set of 10 fields.
type fields10[A, B, C, D, E, F, G, H, I, J any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
}

// Field returns the set with one more field, name, read with src.
func (f fields10[A, B, C, D, E, F, G, H, I, J]) Field[K any](name string, src FieldSource[K]) fields11[A, B, C, D, E, F, G, H, I, J, K] {
	return fields11[A, B, C, D, E, F, G, H, I, J, K]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, f.p9, toPart(name, src)}
}

func (f fields10[A, B, C, D, E, F, G, H, I, J]) object() object10[A, B, C, D, E, F, G, H, I, J] {
	return object10[A, B, C, D, E, F, G, H, I, J]{f: f}
}

// object10 builds the decoder of an object of 10 fields.
type object10[A, B, C, D, E, F, G, H, I, J any] struct {
	f      fields10[A, B, C, D, E, F, G, H, I, J]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object10[A, B, C, D, E, F, G, H, I, J]) Strict() object10[A, B, C, D, E, F, G, H, I, J] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object10[A, B, C, D, E, F, G, H, I, J]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object10[A, B, C, D, E, F, G, H, I, J]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object10[A, B, C, D, E, F, G, H, I, J]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields11 is a set of 11 fields.
type fields11[A, B, C, D, E, F, G, H, I, J, K any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
	p10   part[K]
}

// Field returns the set with one more field, name, read with src.
func (f fields11[A, B, C, D, E, F, G, H, I, J, K]) Field[L any](name string, src FieldSource[L]) fields12[A, B, C, D, E, F, G, H, I, J, K, L] {
	return fields12[A, B, C, D, E, F, G, H, I, J, K, L]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, f.p9, f.p10, toPart(name, src)}
}

func (f fields11[A, B, C, D, E, F, G, H, I, J, K]) object() object11[A, B, C, D, E, F, G, H, I, J, K] {
	return object11[A, B, C, D, E, F, G, H, I, J, K]{f: f}
}

// object11 builds the decoder of an object of 11 fields.
type object11[A, B, C, D, E, F, G, H, I, J, K any] struct {
	f      fields11[A, B, C, D, E, F, G, H, I, J, K]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object11[A, B, C, D, E, F, G, H, I, J, K]) Strict() object11[A, B, C, D, E, F, G, H, I, J, K] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object11[A, B, C, D, E, F, G, H, I, J, K]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J, K) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J, v10 K) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object11[A, B, C, D, E, F, G, H, I, J, K]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J, K) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object11[A, B, C, D, E, F, G, H, I, J, K]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields12 is a set of 12 fields.
type fields12[A, B, C, D, E, F, G, H, I, J, K, L any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
	p10   part[K]
	p11   part[L]
}

// Field returns the set with one more field, name, read with src.
func (f fields12[A, B, C, D, E, F, G, H, I, J, K, L]) Field[M any](name string, src FieldSource[M]) fields13[A, B, C, D, E, F, G, H, I, J, K, L, M] {
	return fields13[A, B, C, D, E, F, G, H, I, J, K, L, M]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, f.p9, f.p10, f.p11, toPart(name, src)}
}

func (f fields12[A, B, C, D, E, F, G, H, I, J, K, L]) object() object12[A, B, C, D, E, F, G, H, I, J, K, L] {
	return object12[A, B, C, D, E, F, G, H, I, J, K, L]{f: f}
}

// object12 builds the decoder of an object of 12 fields.
type object12[A, B, C, D, E, F, G, H, I, J, K, L any] struct {
	f      fields12[A, B, C, D, E, F, G, H, I, J, K, L]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object12[A, B, C, D, E, F, G, H, I, J, K, L]) Strict() object12[A, B, C, D, E, F, G, H, I, J, K, L] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object12[A, B, C, D, E, F, G, H, I, J, K, L]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J, v10 K, v11 L) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object12[A, B, C, D, E, F, G, H, I, J, K, L]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object12[A, B, C, D, E, F, G, H, I, J, K, L]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields13 is a set of 13 fields.
type fields13[A, B, C, D, E, F, G, H, I, J, K, L, M any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
	p10   part[K]
	p11   part[L]
	p12   part[M]
}

// Field returns the set with one more field, name, read with src.
func (f fields13[A, B, C, D, E, F, G, H, I, J, K, L, M]) Field[N any](name string, src FieldSource[N]) fields14[A, B, C, D, E, F, G, H, I, J, K, L, M, N] {
	return fields14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, f.p9, f.p10, f.p11, f.p12, toPart(name, src)}
}

func (f fields13[A, B, C, D, E, F, G, H, I, J, K, L, M]) object() object13[A, B, C, D, E, F, G, H, I, J, K, L, M] {
	return object13[A, B, C, D, E, F, G, H, I, J, K, L, M]{f: f}
}

// object13 builds the decoder of an object of 13 fields.
type object13[A, B, C, D, E, F, G, H, I, J, K, L, M any] struct {
	f      fields13[A, B, C, D, E, F, G, H, I, J, K, L, M]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object13[A, B, C, D, E, F, G, H, I, J, K, L, M]) Strict() object13[A, B, C, D, E, F, G, H, I, J, K, L, M] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object13[A, B, C, D, E, F, G, H, I, J, K, L, M]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J, v10 K, v11 L, v12 M) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object13[A, B, C, D, E, F, G, H, I, J, K, L, M]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object13[A, B, C, D, E, F, G, H, I, J, K, L, M]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields14 is a set of 14 fields.
type fields14[A, B, C, D, E, F, G, H, I, J, K, L, M, N any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
	p10   part[K]
	p11   part[L]
	p12   part[M]
	p13   part[N]
}

// Field returns the set with one more field, name, read with src.
func (f fields14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) Field[O any](name string, src FieldSource[O]) fields15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] {
	return fields15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, f.p9, f.p10, f.p11, f.p12, f.p13, toPart(name, src)}
}

func (f fields14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) object() object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N] {
	return object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]{f: f}
}

// object14 builds the decoder of an object of 14 fields.
type object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N any] struct {
	f      fields14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) Strict() object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J, v10 K, v11 L, v12 M, v13 N) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		v13 := read(&c, o.f.p13, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		v13 := read(&c, o.f.p13, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields15 is a set of 15 fields.
type fields15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
	p10   part[K]
	p11   part[L]
	p12   part[M]
	p13   part[N]
	p14   part[O]
}

// Field returns the set with one more field, name, read with src.
func (f fields15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) Field[P any](name string, src FieldSource[P]) fields16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] {
	return fields16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]{append(slices.Clip(f.names), name), f.p0, f.p1, f.p2, f.p3, f.p4, f.p5, f.p6, f.p7, f.p8, f.p9, f.p10, f.p11, f.p12, f.p13, f.p14, toPart(name, src)}
}

func (f fields15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) object() object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] {
	return object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]{f: f}
}

// object15 builds the decoder of an object of 15 fields.
type object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O any] struct {
	f      fields15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) Strict() object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J, v10 K, v11 L, v12 M, v13 N, v14 O) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		v13 := read(&c, o.f.p13, m, at)
		v14 := read(&c, o.f.p14, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		v13 := read(&c, o.f.p13, m, at)
		v14 := read(&c, o.f.p14, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, at)
		return fromAbsoluteError(v, err)
	}}
}

// fields16 is a set of 16 fields.
type fields16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P any] struct {
	names []string
	p0    part[A]
	p1    part[B]
	p2    part[C]
	p3    part[D]
	p4    part[E]
	p5    part[F]
	p6    part[G]
	p7    part[H]
	p8    part[I]
	p9    part[J]
	p10   part[K]
	p11   part[L]
	p12   part[M]
	p13   part[N]
	p14   part[O]
	p15   part[P]
}

func (f fields16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) object() object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] {
	return object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]{f: f}
}

// object16 builds the decoder of an object of 16 fields.
type object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P any] struct {
	f      fields16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
	strict bool
}

// Strict reports unknown_field for each member the fields do not name.
func (o object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) Strict() object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] {
	o.strict = true
	return o
}

// Map returns the decoder that builds the value with fn once every field
// has decoded.
func (o object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) Map[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) R) Decoder[any, R] {
	return o.AndThen(func(v0 A, v1 B, v2 C, v3 D, v4 E, v5 F, v6 G, v7 H, v8 I, v9 J, v10 K, v11 L, v12 M, v13 N, v14 O, v15 P) (R, error) {
		return fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15), nil
	})
}

// AndThen returns the decoder that builds the value with fn once every
// field has decoded. Issues fn returns (see Invalid) are reported at the
// object; any other error stops the decode.
func (o object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) AndThen[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		v13 := read(&c, o.f.p13, m, at)
		v14 := read(&c, o.f.p14, m, at)
		v15 := read(&c, o.f.p15, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15)
		return fromRelativeError(v, err, at)
	}}
}

// AndThenWithPath is AndThen for a function that is given the path of the
// object, so it can report an issue at that path or beside it. Unlike
// AndThen, it does not move the issues fn returns: their paths are kept as fn
// gives them, so build them from the path it was given, as at.Key("end").
func (o object16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]) AndThenWithPath[R any](fn func(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Path) (R, error)) Decoder[any, R] {
	return Decoder[any, R]{func(in any, at Path) outcome[R] {
		m, issue := openObject(in, at)
		if issue != nil {
			return invalid[R](*issue)
		}
		var c collector
		v0 := read(&c, o.f.p0, m, at)
		v1 := read(&c, o.f.p1, m, at)
		v2 := read(&c, o.f.p2, m, at)
		v3 := read(&c, o.f.p3, m, at)
		v4 := read(&c, o.f.p4, m, at)
		v5 := read(&c, o.f.p5, m, at)
		v6 := read(&c, o.f.p6, m, at)
		v7 := read(&c, o.f.p7, m, at)
		v8 := read(&c, o.f.p8, m, at)
		v9 := read(&c, o.f.p9, m, at)
		v10 := read(&c, o.f.p10, m, at)
		v11 := read(&c, o.f.p11, m, at)
		v12 := read(&c, o.f.p12, m, at)
		v13 := read(&c, o.f.p13, m, at)
		v14 := read(&c, o.f.p14, m, at)
		v15 := read(&c, o.f.p15, m, at)
		if o.strict {
			c.unknown(m, at, o.f.names)
		}
		if c.failed() {
			return collected[R](&c)
		}
		v, err := fn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, at)
		return fromAbsoluteError(v, err)
	}}
}
