// Command gennorm writes internal/norm/tables.go from internal/gennorm/java_norm.tsv, which holds
// what Java's java.text.Normalizer gives; regenerate that file with scripts/normalization/generate.sh.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
)

type cccRange struct {
	lo, hi rune
	ccc    int
}

type decomposition struct {
	r rune
	s string
}

type composite struct{ a, b, c rune }

func main() {
	f, err := os.Open("internal/gennorm/java_norm.tsv")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	var (
		version    string
		ccc        = map[rune]int{}
		canonical  []decomposition
		compat     []decomposition
		composites []composite
	)
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") {
			version = strings.TrimPrefix(line, "# ")
			continue
		}
		fields := strings.Split(line, "\t")
		switch fields[0] {
		case "C":
			n, err := strconv.Atoi(fields[2])
			if err != nil {
				log.Fatal(err)
			}
			ccc[hex(fields[1])] = n
		case "D":
			canonical = append(canonical, decomposition{hex(fields[1]), seq(fields[2])})
		case "K":
			compat = append(compat, decomposition{hex(fields[1]), seq(fields[2])})
		case "P":
			composites = append(composites, composite{hex(fields[1]), hex(fields[2]), hex(fields[3])})
		default:
			log.Fatalf("unknown record %q", line)
		}
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}

	var ranges []cccRange
	for _, r := range sortedKeys(ccc) {
		if n := len(ranges); n > 0 && ranges[n-1].hi+1 == r && ranges[n-1].ccc == ccc[r] {
			ranges[n-1].hi = r
		} else {
			ranges = append(ranges, cccRange{r, r, ccc[r]})
		}
	}
	slices.SortFunc(canonical, func(x, y decomposition) int { return int(x.r - y.r) })
	slices.SortFunc(compat, func(x, y decomposition) int { return int(x.r - y.r) })
	slices.SortFunc(composites, func(x, y composite) int {
		if x.a != y.a {
			return int(x.a - y.a)
		}
		return int(x.b - y.b)
	})

	minDecomp := min(canonical[0].r, compat[0].r)
	minSecond := composites[0].b
	for _, c := range composites {
		minSecond = min(minSecond, c.b)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/gennorm from %s. DO NOT EDIT.\n\npackage norm\n", version)
	fmt.Fprintf(&b, "\n// The smallest code point with a combining class, a decomposition and a place as the\n"+
		"// second of a composite: below them the tables need not be searched.\n")
	fmt.Fprintf(&b, "const (\n\tminCCC = %#x\n\tminDecomp = %#x\n\tminSecond = %#x\n)\n", ranges[0].lo, minDecomp, minSecond)
	b.WriteString("\nvar cccRanges = []cccRange{\n")
	for _, r := range ranges {
		fmt.Fprintf(&b, "\t{%#x, %#x, %d},\n", r.lo, r.hi, r.ccc)
	}
	b.WriteString("}\n")
	writeDecomps(&b, "canonicalDecomps", canonical)
	writeDecomps(&b, "compatDecomps", compat)
	b.WriteString("\nvar composites = []composite{\n")
	for _, c := range composites {
		fmt.Fprintf(&b, "\t{%#x, %#x, %#x},\n", c.a, c.b, c.c)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("internal/norm/tables.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}

func writeDecomps(b *bytes.Buffer, name string, ds []decomposition) {
	fmt.Fprintf(b, "\nvar %s = []decomposition{\n", name)
	for _, d := range ds {
		fmt.Fprintf(b, "\t{%#x, %+q},\n", d.r, d.s)
	}
	b.WriteString("}\n")
}

func hex(s string) rune {
	n, err := strconv.ParseInt(s, 16, 32)
	if err != nil {
		log.Fatal(err)
	}
	return rune(n)
}

func seq(s string) string {
	var b strings.Builder
	for _, h := range strings.Fields(s) {
		b.WriteRune(hex(h))
	}
	return b.String()
}

func sortedKeys(m map[rune]int) []rune {
	keys := make([]rune, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}
