// Command gencase writes casing_table.go: the code points where Java's String.toUpperCase and
// toLowerCase with Locale.ROOT map a code point on its own to something other than Go's
// unicode.ToUpper and unicode.ToLower do. java_casing.tsv holds Java's mappings; regenerate it
// with scripts/casing/generate.sh.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func main() {
	f, err := os.Open("internal/gencase/java_casing.tsv")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	java := map[string]map[rune]string{"U": {}, "L": {}}
	var version string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") {
			version = strings.TrimPrefix(line, "# ")
			continue
		}
		fields := strings.Split(line, "\t")
		cp, err := strconv.ParseInt(fields[1], 16, 32)
		if err != nil {
			log.Fatal(err)
		}
		var to strings.Builder
		for _, h := range strings.Fields(fields[2]) {
			c, err := strconv.ParseInt(h, 16, 32)
			if err != nil {
				log.Fatal(err)
			}
			to.WriteRune(rune(c))
		}
		java[fields[0]][rune(cp)] = to.String()
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/gencase from %s. DO NOT EDIT.\n\npackage raoh\n", version)
	write(&b, "upperExceptions", java["U"], unicode.ToUpper)
	write(&b, "lowerExceptions", java["L"], unicode.ToLower)
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("casing_table.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// write writes the code points where Java's mapping differs from goMap's.
func write(b *bytes.Buffer, name string, java map[rune]string, goMap func(rune) rune) {
	fmt.Fprintf(b, "\nvar %s = map[rune]string{\n", name)
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if !utf8.ValidRune(r) {
			continue
		}
		want, ok := java[r]
		if !ok {
			want = string(r)
		}
		if want != string(goMap(r)) {
			fmt.Fprintf(b, "\t%#x: %+q,\n", r, want)
		}
	}
	b.WriteString("}\n")
}
